site_name: AZ-700 Study Guide

nav:
    - Skills Measured: 'index.md'
    - 'Hybrid Networking':
        - 'S2S VPN connection':
          - 'vpn/s2s.md'
        - 'P2S VPN connection':
          - 'vpn/p2s.md'
        - 'Express Route':
          - 'vpn/exp-route.md'       
    - 'Core Networking':
        - 'Private IP for VNets':
          - 'core/private-ip-vnet.md'
        - 'Name Resolution':
          - 'core/naming.md'
        - 'cross-VNet connectivity':
          - 'core/cross-vnet.md'          
        - 'Virtual WAN':
          - 'core/vwan.md'  
    - 'Routing':
        - 'VNet Routing':
          - 'routing/appgw.md'
        - 'Load Balancers':
          - 'routing/fd.md'
        - 'Application Gateway':
          - 'routing/lb.md'    
        - 'Front Door':
          - 'routing/tfmanager.md'     
        - 'Traffic Manager':
          - 'routing/vnat.md'      
        - 'Virtual Network NAT':
          - 'routing/vnetroute.md'                                       
    - 'Secure Networks':
       - 'Azure Firewall':
          - 'secmon/fw.md'
       - 'NSG':
          - 'secmon/nsg.md'
       - 'WAF':
          - 'secmon/waf.md'  
    - 'Monitor Networks':
       - 'secmon/mon.md'
    - 'Core Networking':
        - 'Private Endpoint':
          - 'privend/privend.md'
        - 'Service Endpoint':
          - 'privend/servend.md'
        - 'VNet integration PaaS':
          - 'privend/vnetintpaas.md'        
    - About: 'about.md'
theme:
    name: material
    collapse_by_default: true
# Necessary for search to work properly
    include_search_page: false
    search_index_only: true
    include_homepage_in_sidebar: false
    highlightjs: true
    hijs_languages:
        - python
        - yaml
        - json
        - powershell
        - azurecli
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
extra_javascript:
  - javascript/tabhack.js